apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hi1d40cvf-python 
  janus-idp.io/tekton: hi1d40cvf-python
  backstage.io/kubernetes-id: hi1d40cvf-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hi1d40cvf-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml