apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: hi1d40cvf-python-gitops
  description: This is GitOps manifest for hi1d40cvf-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=hi1d40cvf-python
    backstage.io/kubernetes-id: hi1d40cvf-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: hi1d40cvf-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:hi1d40cvf-python
