apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hi1d40cvf-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hi1d40cvf-python 
  name: hi1d40cvf-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hi1d40cvf-python 
